// @generated by expo-yarn-workspaces

import { registerRootComponent } from "expo";
import { activateKeepAwake } from "expo-keep-awake";

import MainApp from "../index";

if (__DEV__) {
  activateKeepAwake();
}

registerRootComponent(MainApp);
