export const communityTopics = [
  { value: "activism", label: "Activism" },
  { value: "addiction support", label: "Adiction Support" },
  { value: "animals and pets", label: "Animals and Pets" },
  { value: "anime", label: "Anime" },
  { value: "art", label: "Art" },
  { value: "beauty and makeup", label: "Beauty and Makeup" },
  {
    value: "business, economics, and finances",
    label: "Business, Economics and Finances",
  },
  { value: "carreers", label: "Carrers" },
  { value: "cars and motors vehicles", label: "Cars and motors vehicles" },
  { value: "celebrities", label: "Celebrities" },
  { value: "crafts and DIY", label: "Crafts and DIY" },
  { value: "crypto", label: "Crypto" },
  {
    value: "culture, race, and etnicity",
    label: "Culture, Race, and Etnicity",
  },
  { value: "ethics and philosophy", label: "Ethics and Philosophy" },
  { value: "family and relationships", label: "Family and Relationships" },
  { value: "fashion", label: "Fashion" },
  { value: "fitness and nutrition", label: "Fitness and Nutrition" },
  { value: "food and drink", label: "Food and Drink" },
  { value: "funny/humor", label: "Funny/Humor" },
  { value: "gaming", label: "Gaming" },
  { value: "gender", label: "Gender" },
  { value: "history", label: "History" },
  { value: "hobbies", label: "Hobbies" },
  { value: "home and garden", label: "Home and Garden" },
  { value: "internet culture and memes", label: "Internet Culture and Memes" },
  { value: "law", label: "Law" },
  { value: "learning and education", label: "Learning and Education" },
  { value: "marketplace and deals", label: "Marketplace and Deals" },
  {
    value: "mature themes and adult content",
    label: "Mature Themes and Adult Content",
  },
  { value: "medial and mental health", label: "Medical and Mental Health" },
  { value: "men's health", label: "Men's Health" },
  { value: "meta/reddit", label: "Meta/Reddit" },
  { value: "military", label: "Military" },
  { value: "movies", label: "Movies" },
  { value: "music", label: "Music" },
  { value: "outdoors and nature", label: "Outdoors and Nature" },
  { value: "place", label: "Place" },
  { value: "podcasts and streamers", label: "Podcasts and Streamers" },
  { value: "programming", label: "Programming" },
  {
    value: "reading, writing, and literature",
    label: "Reading, Writing, and Literature",
  },
  { value: "religion and spirituality", label: "Religion and Spirituality" },
  { value: "science", label: "Science" },
  { value: "sexual orientation", label: "Sexual Orientation" },
  { value: "sports", label: "Sports" },
  { value: "tabletop games", label: "Tabletop Games" },
  { value: "technology", label: "Techonology" },
  { value: "television", label: "Television" },
  { value: "trauma support", label: "Trauma Support" },
  { value: "travel", label: "Travel" },
  { value: "woman's health", label: "Woman's Health" },
  { value: "world news", label: "World News" },
  { value: "none of these topics", label: "None of These Topics" },
];
